export const windDirectionToVN = (windDirection: string) => {
  return windDirection == 'S'
    ? 'N'
    : windDirection == 'N'
      ? 'B'
      : windDirection == 'E'
        ? 'Đ'
        : windDirection == 'W'
          ? 'T'
          : windDirection == 'SE'
            ? 'ĐN'
            : windDirection == 'SW'
              ? 'TN'
              : windDirection == 'NE'
                ? 'ĐB'
                : windDirection == 'NW'
                  ? 'TB'
                  : windDirection == 'SSE'
                    ? 'NĐN'
                    : windDirection == 'SSW'
                      ? 'NTN'
                      : windDirection == 'NNE'
                        ? 'BĐB'
                        : windDirection == 'NNW'
                          ? 'BTB'
                          : windDirection == 'ESE'
                            ? 'ĐĐN'
                            : windDirection == 'WSW'
                              ? 'TTN'
                              : windDirection == 'ENE'
                                ? 'ĐĐB'
                                : windDirection == 'WNW'
                                  ? 'TTB'
                                  : ''
}
